import type { NextPage } from 'next'
import dynamic from 'next/dynamic'
import Head from 'next/head'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  const DynamicComponentWithNoSSR = dynamic(() => import('../components/nossr/ebook-viewer'), {
    ssr: false
})

  return (
    <div className={styles.container}>
      <Head>
        <title>Text with ebook viewer (by react-reader library)</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <DynamicComponentWithNoSSR url="https://react-reader.metabits.no/files/alice.epub"/>

    </div>
  )
}

export default Home
